version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bnexdb
      POSTGRES_USER: bnex
      POSTGRES_PASSWORD: bnexpwd
    ports:
      - "5432:5432"

  backend:
    build: ../backend/Backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://bnex:bnexpwd@db:5432/bnexdb
 
  frontend:
    build: 
      context: ../frontend/bnexfront
    depends_on:
      - backend
    ports:
      - "3000:80"
    env_file:
      - ../frontend/bnexfront/.env

volumes:
  postgres_data:
