version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bnexdb
      POSTGRES_USER: bnex
      POSTGRES_PASSWORD: bnexpwd
    ports:
      - "5432:5432"

  backend:
    build: ../backend/Backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://bnex:bnexpwd@db:5432/bnexdb
 
  frontend:
    build: ../frontend/bnexfront
    volumes:
      - ../frontend/bnexfront:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://ec2-44-204-169-176.compute-1.amazonaws.com"
    depends_on:
      - backend
volumes:
  postgres_data:
