version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bnexdb
      POSTGRES_USER: bnex
      POSTGRES_PASSWORD: bnexpwd
    network_mode: "host"

  backend:
    image: python:3.11
    command: >
      /bin/bash -c "
      pip install -r /code/requirements.txt && 
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000 &&
      echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('admin', 'admin@example.com', 'pass') if not User.objects.filter(username='admin').exists() else print('Superuser already exists.')\" | python manage.py shell
      "
    volumes:
      - /home/ec2-user/BNEXCrud/backend/Backend:/code
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bnex:bnexpwd@ec2-44-204-169-176.compute-1.amazonaws.com:5432/bnexdb
    working_dir: /code
    network_mode: "host"

  frontend:
    image: node:latest
    command: /bin/bash -c "npm install && npm start"
    volumes:
      - /home/ec2-user/BNEXCrud/frontend/bnexfront:/app 
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://ec2-44-204-169-176.compute-1.amazonaws.com/:8000
    working_dir: /app
    network_mode: "host"

volumes:
  postgres_data:
