version: '3.8'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bnexdb
      POSTGRES_USER: bnex
      POSTGRES_PASSWORD: bnexpwd

  backend:
    image: python:3.11
    command: /bin/bash -c "pip install -r /code/requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - /home/ec2-user/BNEXCrud/backend/Backend:/code
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://bnex:bnexpwd@db:5432/bnexdb
    working_dir: /code
    ports:
      - "8000:8000"

  frontend:
    image: node:latest
    command: /bin/bash -c "npm install && npm start"
    volumes:
      - /home/ec2-user/BNEXCrud/frontend/bnexfront:/app 
      - /app/node_modules
    ports:
      - "3000:3000" 
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    working_dir: /app

volumes:
  postgres_data:
